# Generated by Django 5.1.7 on 2025-03-26 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='customer',
            name='newsletter',
            field=models.BooleanField(default=False),
        ),
    ]
