# Generated by Django 5.1.7 on 2025-03-26 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_customer_email_customer_newsletter'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='account_balance',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
